name: CacheLib CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.31'

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build project
        run: cmake --build build --parallel

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

